/**
 * Tokenizer for Zig Object Notation (ZON).
 *
 * @see {@link https://ziglang.org/documentation/0.16.0/std/#std.zon|Zig's ZON module}
 *
 * @module
 */

import type { PreserveCommentsOptions } from "./types.ts";

/**
 * Represents the type of a ZON token.
 *
 * @enum {string}
 */
export const TokenType = {
  /** The dot symbol ('.') */
  Period: "Period",
  /** The equals symbol ('=') */
  Equal: "Equal",
  /** The comma symbol (',') */
  Comma: "Comma",
  /** The left brace symbol ('{') */
  LBrace: "LBrace",
  /** The right brace symbol ('}') */
  RBrace: "RBrace",
  /** The minus symbol ('-') */
  Minus: "Minus",
  /** The plus symbol ('+') */
  Plus: "Plus",
  /** An identifier (e.g., field name, true, false, null) */
  Identifier: "Identifier",
  /** A string literal wrapped in double quotes */
  StringLiteral: "StringLiteral",
  /** A multiline string literal starting with '\\\\' */
  MultilineString: "MultilineString",
  /** A character literal wrapped in single quotes */
  CharLiteral: "CharLiteral",
  /** A numeric literal (integer or float, decimal, hex, octal, binary) */
  NumberLiteral: "NumberLiteral",
  /** The end of file token */
  Eof: "Eof",
} as const;

/**
 * Represents the type of a ZON token.
 */
export type TokenType = (typeof TokenType)[keyof typeof TokenType];

/**
 * Raw comment token extracted during lexical analysis.
 */
export interface RawComment {
  /** The kind of comment: file doc (`//!`), doc (`///`), or normal line (`//`). */
  kind: "file" | "doc" | "line";
  /** The text content of the comment (excluding the leading slashes). */
  text: string;
}

/**
 * Represents a token generated by the Tokenizer.
 */
export interface Token {
  /** The type of the token. */
  type: TokenType;
  /** The raw string value of the token. */
  value: string;
  /** The start index of the token in the input string. */
  start: number;
  /** The end index of the token in the input string. */
  end: number;
  /** The 1-based line number of the token. */
  line: number;
  /** The 1-based column number of the token. */
  col: number;
  /** Comments that appeared before this token on preceding lines. */
  leadingComments?: RawComment[];
  /** Trailing comment that appeared on the same line after previous token. */
  trailingComment?: RawComment;
}

/**
 * A tokenizer for Zig Object Notation (ZON) input strings.
 */
export class Tokenizer {
  /** The input ZON string to tokenize. */
  private input: string;
  /** The length of the input ZON string. */
  private length: number;
  /** The current byte index in the input string. */
  private index: number = 0;
  /** The current line number (1-based). */
  private line: number = 1;
  /** The current column number (1-based). */
  private col: number = 1;

  private preserveComments: boolean;
  private keepNormal: boolean = true;
  private keepDoc: boolean = true;
  private keepFileDoc: boolean = true;
  private lastTokenEndLine: number = 0;

  /**
   * Creates a new Tokenizer instance.
   * @param input The input ZON string to tokenize.
   * @param preserveComments Options for comment preservation, or boolean.
   */
  constructor(
    input: string,
    preserveComments?: boolean | PreserveCommentsOptions,
  ) {
    this.input = input;
    this.preserveComments = !!preserveComments;
    if (typeof preserveComments === "object") {
      this.keepNormal = preserveComments.normal ?? true;
      this.keepDoc = preserveComments.doc ?? true;
      this.keepFileDoc = preserveComments.fileDoc ?? true;
    }
    // Skip UTF-8 BOM if present
    if (input.startsWith("\uFEFF")) {
      this.index = 1;
    } else if (
      input.length >= 3 &&
      input.charCodeAt(0) === 0xef &&
      input.charCodeAt(1) === 0xbb &&
      input.charCodeAt(2) === 0xbf
    ) {
      this.index = 3;
    }
    this.length = input.length;
  }

  /**
   * Peeks at the character at the current index.
   * @returns The character at the current index, or an empty string if EOF.
   */
  private peek(): string {
    if (this.index >= this.length) return "";
    return this.input[this.index];
  }

  /**
   * Peeks at the character after the current index.
   * @returns The character after the current index, or an empty string if EOF.
   */
  private peekNext(): string {
    if (this.index + 1 >= this.length) return "";
    return this.input[this.index + 1];
  }

  /**
   * Advances the tokenizer by one character.
   * @returns The advanced character.
   */
  private advance(): string {
    if (this.index >= this.length) return "";
    const char = this.input[this.index];
    this.index++;
    if (char === "\n") {
      this.line++;
      this.col = 1;
    } else {
      this.col++;
    }
    return char;
  }

  /**
   * Checks if a character is an alphabetical character or underscore.
   * @param c The character to check.
   * @returns True if the character is alphabetical, false otherwise.
   */
  private isAlpha(c: string): boolean {
    return (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_";
  }

  /**
   * Checks if a character is alphanumeric or underscore.
   * @param c The character to check.
   * @returns True if the character is alphanumeric, false otherwise.
   */
  private isAlphanumeric(c: string): boolean {
    return this.isAlpha(c) || (c >= "0" && c <= "9");
  }

  /**
   * Skips whitespace and line comments.
   */
  private skipWhitespaceAndComments(): {
    trailingComment?: RawComment;
    leadingComments?: RawComment[];
  } {
    let hadNewline = false;
    let trailingComment: RawComment | undefined;
    const leadingComments: RawComment[] = [];

    while (this.index < this.length) {
      const c = this.peek();
      if (c === " " || c === "\t") {
        this.advance();
      } else if (c === "\r" || c === "\n") {
        hadNewline = true;
        this.advance();
      } else if (c === "/" && this.peekNext() === "/") {
        if (!this.preserveComments) {
          // Fast skip: comments discarded with zero overhead
          this.advance();
          this.advance();
          while (this.index < this.length) {
            const commentChar = this.peek();
            if (commentChar === "\n" || commentChar === "\r") {
              break;
            }
            this.advance();
          }
        } else {
          // Preserving comments
          this.advance(); // /
          this.advance(); // /
          let kind: "file" | "doc" | "line" = "line";
          if (this.peek() === "!") {
            kind = "file";
            this.advance();
          } else if (this.peek() === "/") {
            kind = "doc";
            this.advance();
          }

          const startIdx = this.index;
          while (this.index < this.length) {
            const commentChar = this.peek();
            if (commentChar === "\n" || commentChar === "\r") {
              break;
            }
            this.advance();
          }
          const text = this.input.substring(startIdx, this.index);

          const shouldKeep = (kind === "file" && this.keepFileDoc) ||
            (kind === "doc" && this.keepDoc) ||
            (kind === "line" && this.keepNormal);

          if (shouldKeep) {
            const isTrailing = !hadNewline && this.lastTokenEndLine > 0;
            if (isTrailing && !trailingComment) {
              trailingComment = { kind, text };
            } else {
              leadingComments.push({ kind, text });
            }
          }
        }
      } else {
        break;
      }
    }

    return {
      trailingComment,
      leadingComments: leadingComments.length > 0 ? leadingComments : undefined,
    };
  }

  /**
   * Constructs a token and updates the last token line for trailing comment detection.
   */
  private makeToken(
    type: TokenType,
    value: string,
    start: number,
    line: number,
    col: number,
    comments: {
      trailingComment?: RawComment;
      leadingComments?: RawComment[];
    },
  ): Token {
    this.lastTokenEndLine = this.line;
    return {
      type,
      value,
      start,
      end: this.index,
      line,
      col,
      leadingComments: comments.leadingComments,
      trailingComment: comments.trailingComment,
    };
  }

  /**
   * Retrieves the next token from the input.
   *
   * @returns The next parsed {@link Token}, or an {@link TokenType.Eof} token if the end of input is reached.
   * @throws {Error} If an unterminated literal or invalid escape is encountered.
   */
  public next(): Token {
    const comments = this.skipWhitespaceAndComments();

    const start = this.index;
    const line = this.line;
    const col = this.col;

    if (this.index >= this.length) {
      return this.makeToken(TokenType.Eof, "", start, line, col, comments);
    }

    const c = this.peek();

    // Multiline string
    if (c === "\\" && this.peekNext() === "\\") {
      this.advance();
      this.advance();
      while (this.index < this.length) {
        const nextC = this.peek();
        if (nextC === "\n" || nextC === "\r") {
          break;
        }
        this.advance();
      }
      return this.makeToken(
        TokenType.MultilineString,
        this.input.substring(start, this.index),
        start,
        line,
        col,
        comments,
      );
    }

    // Symbol tokens
    switch (c) {
      case ".":
        this.advance();
        return this.makeToken(
          TokenType.Period,
          ".",
          start,
          line,
          col,
          comments,
        );
      case "=":
        this.advance();
        return this.makeToken(TokenType.Equal, "=", start, line, col, comments);
      case ",":
        this.advance();
        return this.makeToken(TokenType.Comma, ",", start, line, col, comments);
      case "{":
        this.advance();
        return this.makeToken(
          TokenType.LBrace,
          "{",
          start,
          line,
          col,
          comments,
        );
      case "}":
        this.advance();
        return this.makeToken(
          TokenType.RBrace,
          "}",
          start,
          line,
          col,
          comments,
        );
      case "-":
        this.advance();
        return this.makeToken(TokenType.Minus, "-", start, line, col, comments);
      case "+":
        this.advance();
        return this.makeToken(TokenType.Plus, "+", start, line, col, comments);
    }

    // @"..." Identifier
    if (c === "@" && this.peekNext() === '"') {
      this.advance(); // @
      this.advance(); // "
      while (this.index < this.length) {
        const nextC = this.peek();
        if (nextC === '"') {
          this.advance(); // closing "
          return this.makeToken(
            TokenType.Identifier,
            this.input.substring(start, this.index),
            start,
            line,
            col,
            comments,
          );
        } else if (nextC === "\\") {
          this.advance();
          if (this.index >= this.length) {
            throw new Error(
              `Unterminated escape sequence in identifier at line ${line}, col ${col}`,
            );
          }
          this.advance();
        } else if (nextC === "\n" || nextC === "\r") {
          throw new Error(
            `Unterminated identifier (newline found) at line ${line}, col ${col}`,
          );
        } else {
          this.advance();
        }
      }
      throw new Error(`Unterminated identifier at line ${line}, col ${col}`);
    }

    // String literal
    if (c === '"') {
      this.advance(); // "
      while (this.index < this.length) {
        const nextC = this.peek();
        if (nextC === '"') {
          this.advance(); // closing "
          return this.makeToken(
            TokenType.StringLiteral,
            this.input.substring(start, this.index),
            start,
            line,
            col,
            comments,
          );
        } else if (nextC === "\\") {
          this.advance();
          if (this.index >= this.length) {
            throw new Error(
              `Unterminated escape sequence in string literal at line ${line}, col ${col}`,
            );
          }
          this.advance();
        } else if (nextC === "\n" || nextC === "\r") {
          throw new Error(
            `Unterminated string literal (newline found) at line ${line}, col ${col}`,
          );
        } else {
          this.advance();
        }
      }
      throw new Error(
        `Unterminated string literal at line ${line}, col ${col}`,
      );
    }

    // Character literal
    if (c === "'") {
      this.advance(); // '
      while (this.index < this.length) {
        const nextC = this.peek();
        if (nextC === "'") {
          this.advance(); // closing '
          return this.makeToken(
            TokenType.CharLiteral,
            this.input.substring(start, this.index),
            start,
            line,
            col,
            comments,
          );
        } else if (nextC === "\\") {
          this.advance();
          if (this.index >= this.length) {
            throw new Error(
              `Unterminated escape sequence in character literal at line ${line}, col ${col}`,
            );
          }
          this.advance();
        } else if (nextC === "\n" || nextC === "\r") {
          throw new Error(
            `Unterminated character literal (newline found) at line ${line}, col ${col}`,
          );
        } else {
          this.advance();
        }
      }
      throw new Error(
        `Unterminated character literal at line ${line}, col ${col}`,
      );
    }

    // Number literal
    if (c >= "0" && c <= "9") {
      const matchStr = this.scanNumberLiteral();
      return this.makeToken(
        TokenType.NumberLiteral,
        matchStr,
        start,
        line,
        col,
        comments,
      );
    }

    // Standard Identifier
    if (this.isAlpha(c)) {
      this.advance();
      while (this.index < this.length && this.isAlphanumeric(this.peek())) {
        this.advance();
      }
      return this.makeToken(
        TokenType.Identifier,
        this.input.substring(start, this.index),
        start,
        line,
        col,
        comments,
      );
    }

    throw new Error(
      `Unexpected character ${JSON.stringify(c)} at line ${line}, col ${col}`,
    );
  }

  /**
   * Scans a number literal from the input.
   * @returns The scanned number literal.
   */
  private scanNumberLiteral(): string {
    const startIdx = this.index;
    const c1 = this.peek();
    const c2 = this.peekNext();

    if (c1 === "0" && (c2 === "x" || c2 === "X")) {
      // Hexadecimal literal
      this.advance(); // '0'
      this.advance(); // 'x'/'X'

      // Consume significand digits
      while (this.index < this.length && this.isHexDigit(this.peek())) {
        this.advance();
      }

      // Optional fraction
      if (this.peek() === "." && this.isHexDigit(this.peekNext())) {
        this.advance(); // '.'
        while (this.index < this.length && this.isHexDigit(this.peek())) {
          this.advance();
        }
      }

      // Optional exponent
      const p = this.peek();
      if (p === "p" || p === "P") {
        // Lookahead to see if there are digits after optional sign
        let offset = 1;
        let nextChar = this.input[this.index + offset];
        if (nextChar === "+" || nextChar === "-") {
          offset++;
          nextChar = this.input[this.index + offset];
        }
        if (nextChar !== undefined && this.isDecDigit(nextChar)) {
          this.advance(); // 'p'/'P'
          const sign = this.peek();
          if (sign === "+" || sign === "-") {
            this.advance();
          }
          while (this.index < this.length && this.isDecDigit(this.peek())) {
            this.advance();
          }
        }
      }
    } else if (c1 === "0" && (c2 === "b" || c2 === "B")) {
      // Binary literal
      this.advance(); // '0'
      this.advance(); // 'b'/'B'
      while (this.index < this.length && this.isBinDigit(this.peek())) {
        this.advance();
      }
    } else if (c1 === "0" && (c2 === "o" || c2 === "O")) {
      // Octal literal
      this.advance(); // '0'
      this.advance(); // 'o'/'O'
      while (this.index < this.length && this.isOctDigit(this.peek())) {
        this.advance();
      }
    } else {
      // Decimal literal (int or float)
      while (this.index < this.length && this.isDecDigit(this.peek())) {
        this.advance();
      }

      // Optional fraction
      if (this.peek() === "." && this.isDecDigit(this.peekNext())) {
        this.advance(); // '.'
        while (this.index < this.length && this.isDecDigit(this.peek())) {
          this.advance();
        }
      }

      // Optional exponent
      const e = this.peek();
      if (e === "e" || e === "E") {
        let offset = 1;
        let nextChar = this.input[this.index + offset];
        if (nextChar === "+" || nextChar === "-") {
          offset++;
          nextChar = this.input[this.index + offset];
        }
        if (nextChar !== undefined && this.isDecDigit(nextChar)) {
          this.advance(); // 'e'/'E'
          const sign = this.peek();
          if (sign === "+" || sign === "-") {
            this.advance();
          }
          while (this.index < this.length && this.isDecDigit(this.peek())) {
            this.advance();
          }
        }
      }
    }

    return this.input.substring(startIdx, this.index);
  }

  /**
   * Helper to check if a character is a hexadecimal digit or underscore.
   * @param c The character to check.
   * @returns True if the character is a hexadecimal digit or underscore.
   */
  private isHexDigit(c: string): boolean {
    return (c >= "0" && c <= "9") || (c >= "a" && c <= "f") ||
      (c >= "A" && c <= "F") || c === "_";
  }

  /**
   * Helper to check if a character is a decimal digit or underscore.
   * @param c The character to check.
   * @returns True if the character is a decimal digit or underscore.
   */
  private isDecDigit(c: string): boolean {
    return (c >= "0" && c <= "9") || c === "_";
  }

  /**
   * Helper to check if a character is a binary digit or underscore.
   * @param c The character to check.
   * @returns True if the character is a binary digit or underscore.
   */
  private isBinDigit(c: string): boolean {
    return c === "0" || c === "1" || c === "_";
  }

  /**
   * Helper to check if a character is an octal digit or underscore.
   * @param c The character to check.
   * @returns True if the character is an octal digit or underscore.
   */
  private isOctDigit(c: string): boolean {
    return (c >= "0" && c <= "7") || c === "_";
  }
}
