name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Build
        run: deno task build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Run tests
        run: deno task test
